// Generated by AI on 07/25/2026.
// RevenueCat (native iOS/Android in-app purchase) integration, per
// pricing_research.md's "Native mobile billing (RevenueCat)" section.
//
// IMPORTANT: react-native-purchases is a native module. It does NOT work in
// Expo Go — you need a custom dev client / EAS build for iOS and Android
// (see PRICING_IMPLEMENTATION_TESTING.md for setup steps). On web this whole
// module is a no-op; the web app keeps using Stripe Checkout via billing.ts.
import { Platform } from 'react-native';

export type RevenueCatPackage = {
  identifier: string;
  packageType: string;
  product: {
    identifier: string;
    priceString: string;
    price: number;
  };
};

export type RevenueCatCustomerInfo = {
  originalAppUserId: string;
  entitlements: {
    active: Record<string, { identifier: string; productIdentifier: string }>;
  };
};

const IOS_API_KEY = process.env.EXPO_PUBLIC_REVENUECAT_IOS_SDK_KEY || '';
const ANDROID_API_KEY = process.env.EXPO_PUBLIC_REVENUECAT_ANDROID_SDK_KEY || '';

export function isRevenueCatSupported(): boolean {
  return (Platform.OS === 'ios' || Platform.OS === 'android') && !!(IOS_API_KEY || ANDROID_API_KEY);
}

// Lazily require the native module so importing this file never throws on
// web or when the package isn't installed/linked yet (Expo Go).
function getPurchasesModule(): typeof import('react-native-purchases').default | null {
  if (Platform.OS === 'web') return null;
  try {
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    return require('react-native-purchases').default;
  } catch {
    return null;
  }
}

let configuredForAppUserId: string | null = null;

/**
 * Configures the RevenueCat SDK with the account (organization) id as the
 * RevenueCat "app user id" — this is what lets the backend resolve a webhook
 * event straight back to an organization_id with no alias table.
 */
export async function ensureRevenueCatConfigured(appUserId: string): Promise<void> {
  if (!isRevenueCatSupported()) return;
  if (configuredForAppUserId === appUserId) return;

  const Purchases = getPurchasesModule();
  if (!Purchases) {
    throw new Error('react-native-purchases is not available (requires a custom dev client / EAS build, not Expo Go).');
  }
  const apiKey = Platform.OS === 'ios' ? IOS_API_KEY : ANDROID_API_KEY;
  if (!apiKey) {
    throw new Error('RevenueCat SDK key is not configured for this platform (EXPO_PUBLIC_REVENUECAT_IOS_SDK_KEY / EXPO_PUBLIC_REVENUECAT_ANDROID_SDK_KEY).');
  }
  Purchases.configure({ apiKey, appUserID: appUserId });
  configuredForAppUserId = appUserId;
}

// The dashboard uses one Offering per paid plan so each plan's packages are
// unambiguous. The Normal plan lives in RevenueCat's pre-created "default"
// offering (its identifier can't be renamed after creation), so fall back
// through: an offering named exactly after the plan, then the mapped legacy
// identifier, then whatever offering is current.
const LEGACY_OFFERING_IDENTIFIER_BY_PLAN: Record<string, string> = {
  normal: 'default',
};

/**
 * Returns the packages belonging to the offering that represents `plan`.
 * Using the plan's own offering (instead of just the current one) is what
 * keeps a "Pro" selection from silently purchasing a Normal product.
 */
export async function getOfferingPackagesForPlan(plan: string): Promise<RevenueCatPackage[]> {
  const Purchases = getPurchasesModule();
  if (!Purchases) return [];
  const offerings = await Purchases.getOfferings();
  const legacyIdentifier = LEGACY_OFFERING_IDENTIFIER_BY_PLAN[plan];
  const offering =
    offerings.all?.[plan] ||
    (legacyIdentifier ? offerings.all?.[legacyIdentifier] : undefined) ||
    offerings.current;
  return (offering?.availablePackages || []) as unknown as RevenueCatPackage[];
}

export async function purchaseRevenueCatPackage(pkg: RevenueCatPackage): Promise<RevenueCatCustomerInfo> {
  const Purchases = getPurchasesModule();
  if (!Purchases) throw new Error('RevenueCat is not available on this platform.');
  const { customerInfo } = await Purchases.purchasePackage(pkg as never);
  return customerInfo as unknown as RevenueCatCustomerInfo;
}

export async function restoreRevenueCatPurchases(): Promise<RevenueCatCustomerInfo> {
  const Purchases = getPurchasesModule();
  if (!Purchases) throw new Error('RevenueCat is not available on this platform.');
  return (await Purchases.restorePurchases()) as unknown as RevenueCatCustomerInfo;
}

export function activeEntitlementIds(customerInfo: RevenueCatCustomerInfo): string[] {
  return Object.keys(customerInfo.entitlements.active || {});
}
