// Generated by AI on 07/03/2026
import { getJson, patchJson } from './api';

export type LanguagePreference = 'en' | 'zh';

export type UserProfile = {
  id: string;
  email: string;
  first_name: string;
  last_name: string;
  language_preference: LanguagePreference;
};

export async function getMe(): Promise<UserProfile> {
  return getJson<UserProfile>('/users/me');
}

export async function updateLanguagePreference(language: LanguagePreference): Promise<UserProfile> {
  return patchJson<UserProfile>('/users/me', { language_preference: language });
}
