import React, { useEffect, useState } from 'react';
import { ActivityIndicator, AppState, Image, Linking, Platform, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaProvider, SafeAreaView } from 'react-native-safe-area-context';
import { StatusBar } from 'expo-status-bar';

import HomeScreen from './src/screens/HomeScreen';
import LoginScreen from './src/screens/LoginScreen';
import NewPropertyScreen from './src/screens/NewPropertyScreen';
import RecordFormScreen from './src/screens/RecordFormScreen';
import SummaryScreen from './src/screens/SummaryScreen';
import TaxReadyScreen from './src/screens/TaxReadyScreen';
import VerifyEmailScreen from './src/screens/VerifyEmailScreen';
import { Alert } from 'react-native';
import { clearSession, loadSession } from './src/services/api';
import { FinancialRecord } from './src/services/financialRecords';
import { createOrganization, listOrganizations, Organization } from './src/services/organizations';
import { BillingOverview, getBillingOverview, listBillingPlans, openBillingCheckout, openBillingPortal, PlanOption, syncRevenueCatEntitlement } from './src/services/billing';
import { activeEntitlementIds, ensureRevenueCatConfigured, getOfferingPackagesForPlan, isRevenueCatSupported, purchaseRevenueCatPackage, RevenueCatPackage, restoreRevenueCatPurchases } from './src/services/revenueCat';
import { Property } from './src/services/properties';
// Generated by AI on 07/03/2026
import { getMe, LanguagePreference, updateLanguagePreference } from './src/services/users';
import { colors } from './src/theme/tokens';

type HomeTab = 'summary' | 'property' | 'taxReady' | 'account';
type AppScreen = 'boot' | 'login' | 'verify' | 'home' | 'newProperty' | 'recordForm';
type RecordFormDraft = {
  type?: string;
  amount?: string;
  record_date?: string;
  description?: string;
  counterparty?: string;
  category_code?: string;
  sub_type?: string;
  notes?: string;
};

type RecordContext = {
  selectedUnitId?: string;
};

const NAV_ICONS = {
  summary: require('./assets/logo_14.png'),
  property: require('./assets/logo_15.png'),
  taxReady: require('./assets/logo_12.png'),
};

export default function App() {
  const [screen, setScreen] = useState<AppScreen>('boot');
  const [editingProperty, setEditingProperty] = useState<Property | undefined>();
  const [editingRecord, setEditingRecord] = useState<FinancialRecord | undefined>();
  const [recordFormDraft, setRecordFormDraft] = useState<RecordFormDraft | undefined>();
  const [recordContext, setRecordContext] = useState<RecordContext | undefined>();
  const [homeTab, setHomeTab] = useState<HomeTab>('summary');
  const [email, setEmail] = useState('');
  const [userId, setUserId] = useState<string | undefined>();
  const [organizationId, setOrganizationId] = useState<string | undefined>();
  const [organizations, setOrganizations] = useState<Organization[]>([]);
  const [billingOverview, setBillingOverview] = useState<BillingOverview | null>(null);
  const [billingBusy, setBillingBusy] = useState(false);
  // Modified by AI on 07/18/2026. Edit #1.
  // Plan-tier selection state for the account tab's plan card.
  const [selectedPlan, setSelectedPlan] = useState<'normal' | 'pro'>('normal');
  const [selectedInterval, setSelectedInterval] = useState<'month' | 'year'>('month');
  // Modified by AI on 07/25/2026.
  // Plan catalog (with each plan's RevenueCat entitlement id) used to drive
  // the native iOS/Android purchase flow.
  const [planOptions, setPlanOptions] = useState<PlanOption[]>([]);
  const [deliveryMode, setDeliveryMode] = useState<'smtp' | 'outbox' | undefined>();
  const [requestMessage, setRequestMessage] = useState('');
  const [verifyDebugPayload, setVerifyDebugPayload] = useState('');
  const [selectedPropertyId, setSelectedPropertyId] = useState<string | undefined>();
  const [selectedPropertySnapshot, setSelectedPropertySnapshot] = useState<Property | undefined>();
  const [homeRefreshKey, setHomeRefreshKey] = useState(0);
  // Generated by AI on 07/03/2026
  const [language, setLanguage] = useState<LanguagePreference>('en');
  const [languageBusy, setLanguageBusy] = useState(false);

  useEffect(() => {
    (async () => {
      try {
        const stored = await loadSession();
        if (stored) {
          setEmail(stored.session.email);
          setUserId(stored.session.userId);
          setOrganizationId(stored.session.organizationId);
          if (stored.session.userId) {
            const orgs = await listOrganizations(stored.session.userId).catch(() => []);
            setOrganizations(orgs);
          }
          setScreen('home');
          return;
        }
      } catch {}
      setScreen('login');
    })();
  }, []);

  // Modified by AI on 07/31/2026.
  // 'homeTab' is a dependency on purpose: the Plan card lives on the Account
  // tab, so re-entering that tab must refetch. Without it the card kept
  // showing a stale plan (e.g. still "Free" right after a successful
  // purchase) until the whole app was restarted.
  useEffect(() => {
    let cancelled = false;
    (async () => {
      if (!organizationId || screen !== 'home') {
        setBillingOverview(null);
        return;
      }
      try {
        const billing = await getBillingOverview(organizationId);
        if (!cancelled) setBillingOverview(billing);
      } catch {
        if (!cancelled) setBillingOverview(null);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [organizationId, screen, homeTab, homeRefreshKey]);

  // Modified by AI on 07/31/2026.
  // A native in-app purchase backgrounds the app (the store's purchase sheet
  // is a separate activity, and Android may recreate ours). On the way back
  // the mount-time billing fetch can resolve with pre-purchase data and clobber
  // the newer post-sync state, leaving the Plan card stale. Refetching on
  // foreground makes the card self-heal regardless of that ordering.
  useEffect(() => {
    const subscription = AppState.addEventListener('change', (state) => {
      if (state === 'active') setHomeRefreshKey((value) => value + 1);
    });
    return () => subscription.remove();
  }, []);

  // Modified by AI on 07/25/2026.
  // Load the plan catalog once (needed to map a selected plan to its
  // RevenueCat entitlement id for the native purchase flow).
  useEffect(() => {
    if (!isRevenueCatSupported()) return;
    (async () => {
      try {
        const { plans } = await listBillingPlans();
        setPlanOptions(plans);
      } catch {
        setPlanOptions([]);
      }
    })();
  }, []);

  // Generated by AI on 07/03/2026
  // Load the signed-in user's saved language preference.
  useEffect(() => {
    if (screen !== 'home' || !userId) return;
    (async () => {
      try {
        const me = await getMe();
        if (me.language_preference) setLanguage(me.language_preference);
      } catch {
        // Non-fatal: keep the default language.
      }
    })();
  }, [screen, userId]);

  // Generated by AI on 07/03/2026
  const handleChangeLanguage = async (next: LanguagePreference) => {
    if (next === language || languageBusy) return;
    const previous = language;
    setLanguage(next);
    setLanguageBusy(true);
    try {
      await updateLanguagePreference(next);
    } catch (err) {
      setLanguage(previous);
      Alert.alert('Could not update language', err instanceof Error ? err.message : 'Unknown error');
    } finally {
      setLanguageBusy(false);
    }
  };

  const formatMoney = (value?: string | number | null) => {
    const amount = Number(value || 0);
    return amount.toLocaleString('en-US', { style: 'currency', currency: 'USD' });
  };

  const formatCents = (value: number) => formatMoney(value / 100);

  // Modified by AI on 07/18/2026. Edit #1.
  // Plan-tier labels/pricing/actions per pricing_research.md.
  const PLAN_LABELS: Record<string, string> = { free: 'Free', normal: 'Normal', pro: 'Pro' };
  const planName = billingOverview ? PLAN_LABELS[billingOverview.plan] || 'Free' : 'Free';

  // Modified by AI on 07/25/2026.
  // iOS/Android must use RevenueCat (App Store / Play Store in-app purchase)
  // instead of Stripe Checkout — see pricing_research.md "Native mobile
  // billing (RevenueCat)". Web keeps the existing Stripe flow.
  const nativeBillingActive = isRevenueCatSupported();

  // `billingOverview` is null until GET /billing/overview resolves. Treating
  // that as "not free" would both mislabel the button and dereference the
  // null overview in planDescription, so paid state requires a loaded overview.
  const hasPaidPlan = !!billingOverview && billingOverview.plan !== 'free';

  const manageBillingLabel = billingBusy
    ? (nativeBillingActive ? 'Processing...' : 'Opening...')
    : hasPaidPlan && nativeBillingActive
      ? 'Manage subscription'
      : hasPaidPlan && billingOverview?.customer_portal_available
        ? 'Manage billing'
        : nativeBillingActive
          ? `Upgrade to ${PLAN_LABELS[selectedPlan]}`
          : billingOverview?.checkout_available
            ? `Upgrade to ${PLAN_LABELS[selectedPlan]}`
            : billingOverview?.stripe_configured
              ? 'Billing unavailable'
              : 'Set up billing';

  const planDescription = hasPaidPlan && nativeBillingActive
    ? `${formatCents(billingOverview!.amount_per_unit_cents)} per unit / ${billingOverview!.billing_interval}, ${billingOverview!.total_units} unit${billingOverview!.total_units === 1 ? '' : 's'} billed via the App Store/Play Store. Manage or cancel from your device's subscription settings.`
    : hasPaidPlan && billingOverview?.customer_portal_available
      ? `${formatCents(billingOverview!.amount_per_unit_cents)} per unit / ${billingOverview!.billing_interval}, ${billingOverview!.total_units} unit${billingOverview!.total_units === 1 ? '' : 's'} billed. Manage your Stripe subscription and payment method.`
      : billingOverview?.checkout_available || nativeBillingActive
        ? 'Free plan includes unlimited units with a limited voice quota and no tax-ready exports. Pick a plan below to unlock more voice conversions and PDF exports.'
        : 'Billing is not fully configured yet.';

  const voiceQuota = billingOverview?.voice_quota;

  // Modified by AI on 07/25/2026.
  // Runs the native purchase flow: configure RevenueCat with the org id as
  // the app user id, find the package tied to the selected plan's
  // entitlement, purchase it, then sync the result to our backend so the
  // Plan card reflects the new plan immediately.
  async function purchaseSelectedPlanNative() {
    if (!organizationId) return;
    const entitlementId = planOptions.find((option) => option.plan === selectedPlan)?.revenuecat_entitlement_id;
    if (!entitlementId) {
      Alert.alert('Billing', 'This plan is not configured for in-app purchase yet.');
      return;
    }
    await ensureRevenueCatConfigured(organizationId);
    const packages = await getOfferingPackagesForPlan(selectedPlan);
    // The offering is already plan-specific, so only the billing interval has
    // to be matched here. packageType is RevenueCat's normalized duration
    // ("ANNUAL"/"MONTHLY"); fall back to the identifier for custom packages.
    const wantedType = selectedInterval === 'year' ? 'annual' : 'monthly';
    const targetPackage =
      packages.find((pkg) => pkg.packageType?.toLowerCase() === wantedType) ||
      packages.find((pkg) => pkg.identifier.toLowerCase().includes(wantedType)) ||
      packages[0];
    if (!targetPackage) {
      Alert.alert('Billing', 'No purchase options are available right now. Please try again later.');
      return;
    }
    const customerInfo = await purchaseRevenueCatPackage(targetPackage);
    const overview = await syncRevenueCatEntitlement(
      organizationId,
      customerInfo.originalAppUserId || organizationId,
      activeEntitlementIds(customerInfo),
      targetPackage.product.identifier,
      Platform.OS,
    );
    setBillingOverview(overview);
    // Also bump the refresh key so the Plan card still ends up correct if this
    // component was recreated while the store's purchase sheet was in front.
    setHomeRefreshKey((value) => value + 1);
  }

  async function restorePurchasesNative() {
    if (!organizationId) return;
    await ensureRevenueCatConfigured(organizationId);
    const customerInfo = await restoreRevenueCatPurchases();
    const overview = await syncRevenueCatEntitlement(
      organizationId,
      customerInfo.originalAppUserId || organizationId,
      activeEntitlementIds(customerInfo),
      undefined,
      Platform.OS,
    );
    setBillingOverview(overview);
    setHomeRefreshKey((value) => value + 1);
  }

  function openNativeSubscriptionManagement() {
    const url = Platform.OS === 'ios'
      ? 'itms-apps://apps.apple.com/account/subscriptions'
      : 'https://play.google.com/store/account/subscriptions';
    Linking.openURL(url).catch(() => {
      Alert.alert('Billing', 'Could not open subscription settings.');
    });
  }

  return (
    <SafeAreaProvider>
      <StatusBar style="light" />
      {screen === 'boot' && (
        <SafeAreaView style={styles.bootContainer}>
          <Image source={require('./assets/logo_1.png')} style={styles.bootLogo} resizeMode="contain" />
          <ActivityIndicator size="large" color={colors.accent} />
          <Text style={styles.bootText}>Loading RentZu...</Text>
        </SafeAreaView>
      )}
      {screen === 'login' && (
        <LoginScreen
          onSuccess={(result) => {
            setEmail(result.email);
            setUserId(result.user_id);
            setDeliveryMode(result.delivery_mode);
            setRequestMessage(result.message);
            if (result.user_id) {
              listOrganizations(result.user_id).then(setOrganizations).catch(() => undefined);
            }
            if (result.organization_id) {
              setOrganizationId(result.organization_id);
              setScreen('home');
            } else {
              setScreen('verify');
            }
          }}
        />
      )}
      {screen === 'verify' && (
        <VerifyEmailScreen
          email={email}
          deliveryMode={deliveryMode}
          requestMessage={requestMessage}
          onDebugPayload={setVerifyDebugPayload}
          onBack={() => setScreen('login')}
          onVerified={(result) => {
            setUserId(result.user_id);
            setOrganizationId(result.organization_id);
            if (result.user_id) {
              listOrganizations(result.user_id).then(setOrganizations).catch(() => undefined);
            }
            setScreen('home');
          }}
        />
      )}
      {screen === 'verify' && !!verifyDebugPayload && (
        <View style={styles.debugBanner}>
          <Text style={styles.debugBannerText}>{verifyDebugPayload}</Text>
        </View>
      )}
      {screen === 'home' && (
        <View style={styles.appShell}>
          <View style={styles.screenArea}>
            {homeTab === 'summary' && (
              <SummaryScreen
                organizationId={organizationId}
                userId={userId}
                email={email}
                organization={organizations.find((org) => org.id === organizationId)}
                organizations={organizations}
                selectedPropertyId={selectedPropertyId}
                refreshKey={homeRefreshKey}
                onSelectProperty={setSelectedPropertyId}
                onSelectOrganization={setOrganizationId}
                onOpenPropertyTab={() => setHomeTab('property')}
                onOpenNewProperty={() => {
                  setEditingProperty(undefined);
                  setScreen('newProperty');
                }}
                onEditProperty={(property) => {
                  setEditingProperty(property);
                  setScreen('newProperty');
                }}
                onQuickAddRecord={(property) => {
                  setSelectedPropertyId(property.id);
                  setSelectedPropertySnapshot(property);
                  setEditingRecord(undefined);
                  setRecordFormDraft(undefined);
                  setRecordContext(undefined);
                  setScreen('recordForm');
                }}
                onOrganizationUpdated={(updated) => {
                  setOrganizations((prev) => prev.map((org) => (org.id === updated.id ? updated : org)));
                }}
              />
            )}
            {homeTab === 'property' && (
              <HomeScreen
                email={email}
                userId={userId}
                organizationId={organizationId}
                organizations={organizations}
                selectedPropertyId={selectedPropertyId}
                refreshKey={homeRefreshKey}
                onSelectedPropertyChange={setSelectedPropertySnapshot}
                onSelectOrganization={setOrganizationId}
                onBack={() => setHomeTab('summary')}
                onOpenRecordForm={(payload) => {
                  setEditingRecord(payload.record);
                  setRecordFormDraft(payload.draft);
                  setRecordContext({ selectedUnitId: payload.selectedUnitId });
                  if (payload.property) {
                    setSelectedPropertyId(payload.property.id);
                    setSelectedPropertySnapshot(payload.property);
                  }
                  setScreen('recordForm');
                }}
              />
            )}
            {homeTab === 'taxReady' && (
              <TaxReadyScreen
                organizationId={organizationId}
                organizations={organizations}
                selectedPropertyId={selectedPropertyId}
                refreshKey={homeRefreshKey}
                onSelectProperty={setSelectedPropertyId}
                onSelectOrganization={setOrganizationId}
              />
            )}
            {homeTab === 'account' && (
              <SafeAreaView style={styles.accountContainer}>
                <Text style={styles.accountTitle}>Account</Text>
                <Text style={styles.accountEmail}>{email}</Text>
                <ScrollView horizontal showsHorizontalScrollIndicator={false} style={styles.orgBar} contentContainerStyle={styles.orgBarContent}>
                  {!!userId && organizations.length > 0 && (
                    <>
                      {organizations.map((org) => (
                        <Pressable key={org.id} style={[styles.orgChip, org.id === organizationId && styles.orgChipActive]} onPress={() => setOrganizationId(org.id)}>
                          <Text style={[styles.orgChipText, org.id === organizationId && styles.orgChipTextActive]}>{org.name}</Text>
                        </Pressable>
                      ))}
                    </>
                  )}
                </ScrollView>

                <View style={styles.accountCard}>
                  <Text style={styles.accountCardTitle}>Organizations</Text>
                  <Text style={styles.accountCardBody}>Create and switch owner groups from one place.</Text>
                  <Pressable
                    style={styles.primaryActionButton}
                    onPress={async () => {
                      if (!userId) return;
                      try {
                        const nextName = `Workspace ${organizations.length + 1}`;
                        const created = await createOrganization(userId, { name: nextName, entity_type: 'llc' });
                        const orgs = await listOrganizations(userId);
                        setOrganizations(orgs);
                        setOrganizationId(created.id);
                        setHomeRefreshKey((value) => value + 1);
                        Alert.alert('Organization created', `${nextName} is ready. You can rename it next.`);
                      } catch (err) {
                        Alert.alert('Could not create organization', err instanceof Error ? err.message : 'Unknown error');
                      }
                    }}
                  >
                    <Text style={styles.primaryActionButtonText}>Create organization</Text>
                  </Pressable>
                </View>

                <View style={styles.accountCard}>
                  <View style={styles.planHeader}>
                    <Text style={styles.accountCardTitle}>Plan</Text>
                    <View style={styles.proBadge}><Text style={styles.proBadgeText}>{planName}</Text></View>
                  </View>
                  <Text style={styles.planPrice}>
                    {billingOverview ? formatCents(billingOverview.estimated_total_cents || 0) : '$0.00'}
                    <Text style={styles.planPeriod}> / {billingOverview?.billing_interval === 'year' ? 'year' : 'month'}</Text>
                  </Text>
                  <Text style={styles.accountCardBody}>{planDescription}</Text>
                  {!!voiceQuota && (
                    <Text style={styles.accountCardBody}>
                      Voice conversions: {voiceQuota.used}/{voiceQuota.limit} used this period ({voiceQuota.remaining} left).
                    </Text>
                  )}
                  {billingOverview?.plan === 'free' && (
                    <>
                      <View style={styles.languageRow}>
                        {(['normal', 'pro'] as const).map((planOption) => (
                          <Pressable
                            key={planOption}
                            style={[styles.orgChip, selectedPlan === planOption && styles.orgChipActive]}
                            onPress={() => setSelectedPlan(planOption)}
                          >
                            <Text style={[styles.orgChipText, selectedPlan === planOption && styles.orgChipTextActive]}>{PLAN_LABELS[planOption]}</Text>
                          </Pressable>
                        ))}
                      </View>
                      <View style={styles.languageRow}>
                        {(['month', 'year'] as const).map((intervalOption) => (
                          <Pressable
                            key={intervalOption}
                            style={[styles.orgChip, selectedInterval === intervalOption && styles.orgChipActive]}
                            onPress={() => setSelectedInterval(intervalOption)}
                          >
                            <Text style={[styles.orgChipText, selectedInterval === intervalOption && styles.orgChipTextActive]}>{intervalOption === 'month' ? 'Monthly' : 'Yearly'}</Text>
                          </Pressable>
                        ))}
                      </View>
                    </>
                  )}
                  <Pressable
                    style={[
                      styles.primaryActionButton,
                      (!billingBusy && !nativeBillingActive && !billingOverview?.customer_portal_available && !billingOverview?.checkout_available) ? styles.primaryActionButtonDisabled : null,
                    ]}
                    onPress={async () => {
                      if (!organizationId) return;
                      try {
                        setBillingBusy(true);
                        if (nativeBillingActive) {
                          if (hasPaidPlan) {
                            openNativeSubscriptionManagement();
                          } else {
                            await purchaseSelectedPlanNative();
                          }
                        } else if (hasPaidPlan && billingOverview?.customer_portal_available) {
                          await openBillingPortal(organizationId);
                        } else if (billingOverview?.checkout_available) {
                          await openBillingCheckout(organizationId, selectedPlan, selectedInterval);
                        } else if (!billingOverview?.stripe_configured) {
                          Alert.alert('Billing setup needed', 'Stripe is not fully configured on the server yet.');
                        } else {
                          Alert.alert('Billing', 'There is nothing to manage yet for this workspace. Add at least one property first.');
                        }
                      } catch (err) {
                        Alert.alert('Billing', err instanceof Error ? err.message : 'Could not open billing');
                      } finally {
                        setBillingBusy(false);
                      }
                    }}
                    disabled={billingBusy}
                  >
                    <Text style={styles.primaryActionButtonText}>{manageBillingLabel}</Text>
                  </Pressable>
                  {nativeBillingActive && billingOverview?.plan === 'free' && (
                    <Pressable
                      style={styles.linkButton}
                      disabled={billingBusy}
                      onPress={async () => {
                        try {
                          setBillingBusy(true);
                          await restorePurchasesNative();
                        } catch (err) {
                          Alert.alert('Billing', err instanceof Error ? err.message : 'Could not restore purchases');
                        } finally {
                          setBillingBusy(false);
                        }
                      }}
                    >
                      <Text style={styles.linkButtonText}>Restore purchases</Text>
                    </Pressable>
                  )}
                </View>

                {/* Generated by AI on 07/03/2026 */}
                <View style={styles.accountCard}>
                  <Text style={styles.accountCardTitle}>Language</Text>
                  <Text style={styles.accountCardBody}>Choose your preferred language. This also sets the language used for voice-to-text records.</Text>
                  <View style={styles.languageRow}>
                    {([
                      { key: 'en' as LanguagePreference, label: 'English' },
                      { key: 'zh' as LanguagePreference, label: '中文' },
                    ]).map((option) => {
                      const active = language === option.key;
                      return (
                        <Pressable
                          key={option.key}
                          style={[styles.languageOption, active && styles.languageOptionActive]}
                          onPress={() => handleChangeLanguage(option.key)}
                          disabled={languageBusy}
                        >
                          <Text style={[styles.languageOptionText, active && styles.languageOptionTextActive]}>{option.label}</Text>
                        </Pressable>
                      );
                    })}
                  </View>
                </View>

                <Pressable
                  style={styles.logoutButton}
                  onPress={async () => {
                    await clearSession();
                    setEmail('');
                    setUserId(undefined);
                    setOrganizationId(undefined);
                    setOrganizations([]);
                    setScreen('login');
                  }}
                >
                  <Text style={styles.logoutText}>Sign Out</Text>
                </Pressable>
              </SafeAreaView>
            )}
          </View>
          <View style={styles.bottomBar}>
            {([
              { key: 'summary' as HomeTab, label: 'Summary', icon: NAV_ICONS.summary },
              { key: 'property' as HomeTab, label: 'Property', icon: NAV_ICONS.property },
              { key: 'taxReady' as HomeTab, label: 'Tax Ready', icon: NAV_ICONS.taxReady },
              { key: 'account' as HomeTab, label: 'Account', icon: null },
            ]).map((item) => {
              const active = homeTab === item.key;
              return (
                <Pressable key={item.key} style={styles.navItem} onPress={() => setHomeTab(item.key)}>
                  {item.icon ? (
                    <Image source={item.icon} style={[styles.navIconImage, active && styles.navIconImageActive]} resizeMode="contain" />
                  ) : (
                    <Text style={[styles.navIcon, active && styles.navIconActive]}>👤</Text>
                  )}
                  <Text style={[styles.navLabel, active && styles.navLabelActive]}>{item.label}</Text>
                  {active && <View style={styles.navIndicator} />}
                </Pressable>
              );
            })}
          </View>
        </View>
      )}
      {screen === 'newProperty' && (
        <NewPropertyScreen
          organizationId={organizationId}
          initialProperty={editingProperty}
          onBack={() => setScreen('home')}
          onSaved={(property: Property) => {
            setEditingProperty(undefined);
            setSelectedPropertyId(property.id);
            setSelectedPropertySnapshot(property);
            setHomeRefreshKey((value) => value + 1);
            setHomeTab(editingProperty ? 'summary' : 'property');
            setScreen('home');
          }}
        />
      )}
      {screen === 'recordForm' && (
        <RecordFormScreen
          organizationId={organizationId}
          selectedProperty={selectedPropertySnapshot}
          userId={userId}
          selectedUnitId={recordContext?.selectedUnitId}
          initialRecord={editingRecord}
          initialDraft={recordFormDraft}
          onBack={() => {
            setEditingRecord(undefined);
            setRecordFormDraft(undefined);
            setRecordContext(undefined);
            setHomeTab('property');
            setHomeRefreshKey((value) => value + 1);
            setScreen('home');
          }}
          onSaved={() => {
            setEditingRecord(undefined);
            setRecordFormDraft(undefined);
            setRecordContext(undefined);
            setHomeRefreshKey((value) => value + 1);
            setHomeTab('property');
            setScreen('home');
          }}
        />
      )}
    </SafeAreaProvider>
  );
}

const styles = StyleSheet.create({
  bootContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.background,
    padding: 24,
  },
  bootLogo: {
    width: 180,
    height: 60,
    marginBottom: 24,
  },
  bootText: {
    marginTop: 16,
    color: colors.textSecondary,
    fontSize: 16,
    fontWeight: '600',
  },
  appShell: {
    flex: 1,
    backgroundColor: colors.background,
  },
  screenArea: {
    flex: 1,
  },
  accountContainer: {
    flex: 1,
    backgroundColor: colors.background,
    padding: 20,
    paddingTop: 60,
  },
  accountTitle: {
    color: colors.textPrimary,
    fontSize: 28,
    fontWeight: '800',
    marginBottom: 8,
  },
  accountEmail: {
    color: colors.textSecondary,
    fontSize: 14,
    marginBottom: 24,
  },
  orgBar: {
    flexGrow: 0,
    marginBottom: 24,
  },
  orgBarContent: {
    flexDirection: 'row',
    gap: 8,
  },
  orgChip: {
    backgroundColor: colors.accentSoft,
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: colors.accentBorderStrong,
  },
  orgChipActive: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  orgChipText: {
    color: colors.accent,
    fontSize: 13,
    fontWeight: '700',
  },
  orgChipTextActive: {
    color: colors.onAccent,
  },
  accountCard: {
    backgroundColor: colors.card,
    borderRadius: 20,
    padding: 18,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    marginBottom: 16,
  },
  accountCardTitle: {
    color: colors.textPrimary,
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 8,
  },
  accountCardBody: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 20,
    marginBottom: 14,
  },
  primaryActionButton: {
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
    backgroundColor: colors.income,
  },
  primaryActionButtonDisabled: {
    backgroundColor: colors.disabled,
  },
  primaryActionButtonText: {
    color: colors.onAccent,
    fontWeight: '800',
    fontSize: 15,
  },
  linkButton: {
    alignItems: 'center',
    paddingVertical: 10,
  },
  linkButtonText: {
    color: colors.textSecondary,
    fontWeight: '600',
    fontSize: 13,
    textDecorationLine: 'underline',
  },
  planHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  proBadge: {
    backgroundColor: colors.accentSoftStrong,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  proBadgeText: {
    color: colors.accent,
    fontSize: 12,
    fontWeight: '800',
  },
  planPrice: {
    color: colors.textPrimary,
    fontSize: 28,
    fontWeight: '900',
  },
  planPeriod: {
    color: colors.textMuted,
    fontSize: 16,
    fontWeight: '600',
  },
  languageRow: {
    flexDirection: 'row',
    gap: 10,
  },
  languageOption: {
    flex: 1,
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
    backgroundColor: colors.surfaceSlate,
    borderWidth: 1,
    borderColor: colors.cardBorder,
  },
  languageOptionActive: {
    backgroundColor: colors.accentSoftStrong,
    borderColor: colors.accent,
  },
  languageOptionText: {
    color: colors.textSecondary,
    fontWeight: '800',
    fontSize: 15,
  },
  languageOptionTextActive: {
    color: colors.accent,
  },
  logoutButton: {
    backgroundColor: colors.expenseSoft,
    borderRadius: 16,
    paddingVertical: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.expenseBorder,
  },
  logoutText: {
    color: colors.expense,
    fontWeight: '800',
    fontSize: 15,
  },
  debugBanner: {
    backgroundColor: '#111827',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  debugBannerText: {
    color: '#f9fafb',
    fontSize: 11,
    fontWeight: '600',
  },
  bottomBar: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    backgroundColor: colors.cardOpaque,
    borderTopWidth: 1,
    borderColor: colors.cardBorder,
    paddingVertical: 10,
    paddingBottom: 28,
    paddingHorizontal: 8,
  },
  navItem: {
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 70,
    position: 'relative',
  },
  navIconImage: {
    width: 24,
    height: 24,
    opacity: 0.5,
  },
  navIconImageActive: {
    opacity: 1,
  },
  navIcon: {
    fontSize: 22,
    opacity: 0.5,
  },
  navIconActive: {
    opacity: 1,
  },
  navLabel: {
    marginTop: 4,
    fontSize: 11,
    fontWeight: '700',
    color: colors.textMuted,
  },
  navLabelActive: {
    color: colors.accent,
  },
  navIndicator: {
    position: 'absolute',
    top: -10,
    width: 20,
    height: 3,
    borderRadius: 2,
    backgroundColor: colors.accent,
  },
});
