# Generated by AI on 07/25/2026.
# Audit log of RevenueCat webhook deliveries, mirroring billing_event.py for
# Stripe. Keeps a de-dupe key (revenuecat_event_id) since RevenueCat's docs
# warn the same webhook event may be delivered more than once.
from sqlalchemy import Column, DateTime, ForeignKey, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.sql import func

from db import Base


class RevenueCatEvent(Base):
    __tablename__ = 'revenuecat_events'

    id = Column(UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid())
    organization_id = Column(UUID(as_uuid=True), ForeignKey('organizations.id', ondelete='CASCADE'), nullable=False, index=True)
    revenuecat_event_id = Column(Text, unique=True, nullable=False)
    revenuecat_event_type = Column(Text, nullable=False)
    app_user_id = Column(Text)
    product_id = Column(Text)
    entitlement_ids = Column(Text)
    period_type = Column(Text)
    store = Column(Text)
    occurred_at = Column(DateTime(timezone=True))
    raw_payload = Column(Text)
    created_at = Column(DateTime(timezone=True), nullable=False, server_default=func.now())
