// Generated by AI on 07/03/2026
// Shared dark-theme design tokens for the Rentzu app.
// Values mirror the existing hardcoded palette so this is a refactor, not a redesign.

export const colors = {
  // Surfaces
  background: '#0a0e1a',
  card: 'rgba(17,24,39,0.8)',
  cardOpaque: 'rgba(17,24,39,0.98)',
  cardBorder: 'rgba(55,65,81,0.5)',
  menu: '#1e293b',
  surfaceFaint: 'rgba(255,255,255,0.04)',
  surface: 'rgba(255,255,255,0.06)',
  surfaceStrong: 'rgba(255,255,255,0.08)',
  surfaceBright: 'rgba(255,255,255,0.1)',
  surfaceSlate: 'rgba(30,41,59,0.6)',
  disabled: '#334155',
  chartBase: '#111827',

  // Borders / dividers
  border: 'rgba(255,255,255,0.1)',
  borderStrong: 'rgba(255,255,255,0.12)',
  divider: 'rgba(255,255,255,0.05)',
  dividerSubtle: 'rgba(55,65,81,0.3)',

  // Accents
  accent: '#3b82f6',
  accentLight: '#93c5fd',
  accentSoft: 'rgba(59,130,246,0.15)',
  accentSoftStrong: 'rgba(59,130,246,0.2)',
  accentChip: 'rgba(59,130,246,0.12)',
  accentBadge: 'rgba(59,130,246,0.14)',
  accentBorder: 'rgba(59,130,246,0.25)',
  accentBorderStrong: 'rgba(59,130,246,0.3)',
  accentFaint: 'rgba(59,130,246,0.1)',

  income: '#22c55e',
  incomeSoft: 'rgba(34,197,94,0.15)',
  expense: '#ef4444',
  expenseSoft: 'rgba(239,68,68,0.15)',
  expenseBorder: 'rgba(239,68,68,0.3)',
  expenseGlow: 'rgba(239,68,68,0.5)',
  repair: '#8b5cf6',
  repairSoft: 'rgba(139,92,246,0.15)',
  repairSoftStrong: 'rgba(139,92,246,0.2)',
  repairBorder: 'rgba(139,92,246,0.4)',
  repairBorderSoft: 'rgba(139,92,246,0.3)',

  // Text
  textPrimary: '#f1f5f9',
  textSecondary: '#94a3b8',
  textMuted: '#64748b',
  textFaint: '#4b5563',
  onAccent: '#fff',
} as const;

export const spacing = {
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 20,
  xxl: 24,
} as const;

export const radius = {
  sm: 8,
  md: 14,
  lg: 16,
  xl: 20,
  pill: 999,
} as const;

export const fontWeight = {
  semibold: '600',
  bold: '700',
  extrabold: '800',
  black: '900',
} as const;

export const fontSize = {
  xs: 11,
  sm: 12,
  md: 13,
  base: 14,
  lg: 15,
  xl: 16,
  xxl: 18,
  title: 20,
  display: 28,
} as const;
