# Generated by AI on 07/03/2026
from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session

from db import get_db
from dependencies import CurrentUser, get_current_user
from schemas.user import UserPatch, UserRead
from services.users import update_language_preference

router = APIRouter()


@router.get('/me', response_model=UserRead)
def read_me(
    current_user: CurrentUser = Depends(get_current_user),
):
    return current_user.user


@router.patch('/me', response_model=UserRead)
def update_me(
    payload: UserPatch,
    db: Session = Depends(get_db),
    current_user: CurrentUser = Depends(get_current_user),
):
    if payload.language_preference is not None:
        update_language_preference(db, current_user.user, payload.language_preference)
    return current_user.user
