# Generated by AI on 07/15/2026
# Reusable adb/uiautomator helper functions for driving the Rentzu Expo app on the
# Android emulator without guessing tap coordinates from a scaled screenshot.
#
# Usage (dot-source into your session):
#   . D:\apps\rentzu\.agents\skills\rentzu-manual-testing\scripts\ui-helpers.ps1
#   Get-UiDump                                   # refresh the cached dump
#   $b = Get-ElementBounds -Text "Sign Out"      # or -ContentDesc "Account"
#   Tap-Bounds $b
#   Tap-ElementByText "Continue with email"
#   Type-IntoFocusedField "vampirel1988@gmail.com"
#   Take-Screenshot -Name "after-login"
#
# All functions shell out to adb; they assume exactly one device/emulator is attached
# (adb devices). If you have multiple, set $env:ANDROID_SERIAL first.
#
# *** DO NOT add functions here that launch run-server.cmd, run-app.cmd, or
# *** emulator.exe (e.g. via Start-Process, Start-Job, or backgrounding with `&`).
# *** Those three are long-running, log-emitting processes. If they're started
# *** from inside a dot-sourced script or any wrapped/hidden subprocess, their
# *** stdout/stderr is not visible to the user in the CLI - defeating the whole
# *** point of running them. They must ALWAYS be launched as the sole command of
# *** their own top-level `powershell` tool call (see SKILL.md "Visibility
# *** requirement"), each with its own shellId, so the console output streams
# *** back and remains readable via read_powershell at any time. This script only
# *** provides read-only status checks (Get-RentzuSessionStatus, Test-*Healthy,
# *** Get-RunningEmulatorSerial) and UI-driving helpers - never process launches
# *** for the three long-running services.

$script:RentzuUiWorkDir = Join-Path $env:TEMP "rentzu-ui-test"
New-Item -ItemType Directory -Path $script:RentzuUiWorkDir -Force | Out-Null

# Modified by AI on 07/15/2026. Edit #1.
function Read-XmlDump {
    <#
    Reads a uiautomator XML dump as [xml], forcing UTF-8 decoding.
    BUG THIS FIXES: `Get-Content -Raw` on this PowerShell install uses the
    system codepage, not UTF-8, to decode the file. The app's content-desc
    values sometimes contain emoji (multi-byte UTF-8 sequences). Decoding
    those bytes with the wrong codepage doesn't just render mojibake - it can
    misalign the byte stream enough to swallow an adjacent ASCII `"` character,
    which breaks the XML attribute quoting and makes `[xml]$xml = ...` throw
    InvalidCastToXmlDocument ("false" is an unexpected token...). Always read
    uiautomator dumps through this function - never Get-Content -Raw directly.
    #>
    param([Parameter(Mandatory = $true)][string]$Path)
    if (-not (Test-Path $Path)) { throw "No UI dump at $Path - call Get-UiDump first." }
    $text = [System.IO.File]::ReadAllText($Path, [System.Text.Encoding]::UTF8)
    [xml]$xml = $text
    return $xml
}

# ---------------------------------------------------------------------------
# Session lifecycle / conflict handling
# ---------------------------------------------------------------------------
# IMPORTANT - read this before starting the backend, the emulator, or Expo.
#
# The CLI (Copilot CLI / this agent tool) tracks background shells by shellId
# ACROSS TURNS of the same conversation. If you already started the backend,
# emulator, or Expo dev server earlier in this session (shellIds you named e.g.
# "backend", "emulator", "expo"), those processes are STILL RUNNING even after
# your tool call returns - starting them again in a new shellId without first
# checking/stopping the old one causes port conflicts (8000, 8081) and duplicate
# emulator instances.
#
# Correct order of operations every time you are asked to test the app:
#   1. Call `list_powershell` (a CLI tool, not part of this script) and look for
#      existing shellIds whose command matches run-server.cmd / run-app.cmd /
#      emulator.exe. If found and status is "running":
#        a. Health-check them first (Test-RentzuBackendHealthy /
#           Test-RentzuExpoHealthy / Get-RunningEmulatorSerial below). If healthy,
#           REUSE them - do not restart. Restarting a healthy emulator wastes
#           minutes on a cold boot for no benefit.
#        b. Only if a tracked shell is unhealthy/stuck, stop it with
#           `stop_powershell <shellId>` before relaunching that component.
#   2. Regardless of what the CLI shell tracker shows (a fresh CLI session has no
#      memory of shells from a previous one, but the underlying Windows processes
#      from a crashed/abandoned previous run CAN still be alive and holding
#      ports) - run `Get-RentzuSessionStatus` below. It checks the actual OS
#      state (TCP listeners on 8000/8081, adb devices) independent of the CLI's
#      own bookkeeping, and is authoritative.
#   3. Use `Ensure-RentzuBackendClean` / `Ensure-RentzuExpoClean` before starting
#      run-server.cmd / run-app.cmd if `Get-RentzuSessionStatus` reports either
#      port already bound by something other than your current attempt. These
#      kill only the process bound to that port, not everything on the box.
#   4. Use `Get-RunningEmulatorSerial` before launching a new emulator - if an
#      AVD is already booted (state "device"), reuse it. If it shows "offline"
#      (wedged), kill it with `adb -s <serial> emu kill` (fall back to
#      `Stop-Process -Id <pid>` on the emulator process if `emu kill` hangs) and
#      wait a few seconds before booting fresh.
#
# In short: never blindly re-run the three startup commands back-to-back across
# turns/sessions. Always check-then-act. This is what makes it safe for many
# downstream test skills to depend on this one without stepping on each other.

function Get-RentzuSessionStatus {
    <#
    Authoritative, OS-level snapshot of what's already running - independent of
    the CLI's own shellId bookkeeping. Always call this first.
    #>
    $backendPort = Get-NetTCPConnection -LocalPort 8000 -State Listen -ErrorAction SilentlyContinue
    $expoPort = Get-NetTCPConnection -LocalPort 8081 -State Listen -ErrorAction SilentlyContinue
    $backendHealthy = Test-RentzuBackendHealthy
    $expoHealthy = Test-RentzuExpoHealthy
    $emulatorSerial = Get-RunningEmulatorSerial

    [pscustomobject]@{
        BackendPortBound = [bool]$backendPort
        BackendHealthy   = $backendHealthy
        BackendPids      = ($backendPort | Select-Object -ExpandProperty OwningProcess -Unique)
        ExpoPortBound    = [bool]$expoPort
        ExpoHealthy      = $expoHealthy
        ExpoPids         = ($expoPort | Select-Object -ExpandProperty OwningProcess -Unique)
        EmulatorSerial   = $emulatorSerial
        EmulatorRunning  = [bool]$emulatorSerial
    }
}

function Test-RentzuBackendHealthy {
    <#
    Retries before declaring unhealthy, and shells out to curl.exe rather than
    Invoke-WebRequest. Two real incidents happened during development of this
    skill and both must stay fixed:
      1. A single fast timeout falsely flagged a healthy server as dead under
         load (system busy with an emulator running) - hence the retries.
      2. Invoke-WebRequest's `.Content` came back as a raw byte[] (not a decoded
         string) for these plain-text endpoints on this PowerShell install, so
         `-match` against it silently always failed - a healthy server was
         reported unhealthy on every single call, not just occasionally. curl.exe
         returns decoded text directly and sidesteps this entirely; do not
         switch this back to Invoke-WebRequest without verifying `.Content` is
         actually a string on the target PowerShell version first.
    Both bugs manifested identically: this skill's own "clean up if unhealthy"
    logic killed a perfectly good, already-running Expo dev server. Treat any
    change to these two functions as safety-critical - verify with the manual
    curl.exe check in SKILL.md before trusting a change here.
    #>
    param([int]$Attempts = 3, [int]$TimeoutSec = 5, [int]$DelayMs = 1000)
    for ($i = 0; $i -lt $Attempts; $i++) {
        $out = curl.exe -s --max-time $TimeoutSec http://127.0.0.1:8000/ 2>$null
        if ($LASTEXITCODE -eq 0 -and $out -match '"ok":\s*true') { return $true }
        if ($i -lt $Attempts - 1) { Start-Sleep -Milliseconds $DelayMs }
    }
    return $false
}

function Test-RentzuExpoHealthy {
    <# See the reliability note on Test-RentzuBackendHealthy - same reasoning applies. #>
    param([int]$Attempts = 3, [int]$TimeoutSec = 5, [int]$DelayMs = 1000)
    for ($i = 0; $i -lt $Attempts; $i++) {
        $out = curl.exe -s --max-time $TimeoutSec http://127.0.0.1:8081/status 2>$null
        if ($LASTEXITCODE -eq 0 -and $out -match 'packager-status:running') { return $true }
        if ($i -lt $Attempts - 1) { Start-Sleep -Milliseconds $DelayMs }
    }
    return $false
}

function Get-RunningEmulatorSerial {
    <# Returns the serial (e.g. "emulator-5554") of a fully-booted (state "device")
       emulator, or $null if none is running/booted. Ignores "offline"/"unauthorized". #>
    $lines = adb devices 2>$null | Select-String "^emulator-\d+\s+device$"
    if ($lines) { return ($lines[0] -split '\s+')[0] }
    return $null
}

function Stop-ProcessOnPort {
    <# Force-kills whatever process owns the listening socket on -Port. Use this
       instead of a broad taskkill/Stop-Process by name - it only touches the one
       process actually holding the port you care about. DESTRUCTIVE - only call
       this from Ensure-RentzuBackendClean/Ensure-RentzuExpoClean, which gate it
       behind a double-checked "genuinely unhealthy" verdict, never directly on a
       single flaky probe. #>
    param([Parameter(Mandatory)][int]$Port)
    $conns = Get-NetTCPConnection -LocalPort $Port -State Listen -ErrorAction SilentlyContinue
    foreach ($procId in ($conns | Select-Object -ExpandProperty OwningProcess -Unique)) {
        try { Stop-Process -Id $procId -Force -ErrorAction Stop } catch { }
    }
}

function Ensure-RentzuBackendClean {
    <#
    Call before `.\run-server.cmd` if the backend looks unhealthy. Kills ONLY if
    the port is bound AND two independent, retrying health checks both fail (a
    real incident happened where a single-shot 3s timeout falsely flagged a
    healthy Expo server as dead and it got killed - do not weaken this
    double-check back to a single probe). Prints a clear warning before killing
    anything, since this is destructive and should never happen silently.
    run-server.cmd already does its own port-8000 + uvicorn-process cleanup
    internally, so this is a belt-and-suspenders check for when you're not using
    that script.
    #>
    $portBound = [bool](Get-NetTCPConnection -LocalPort 8000 -State Listen -ErrorAction SilentlyContinue)
    if (-not $portBound) { return }
    if (Test-RentzuBackendHealthy) { return }
    Start-Sleep -Seconds 2
    if (Test-RentzuBackendHealthy) { return }
    Write-Warning "Backend on port 8000 is bound but failed health checks twice - stopping it so a fresh instance can start."
    Stop-ProcessOnPort -Port 8000
    Start-Sleep -Seconds 2
}

function Ensure-RentzuExpoClean {
    <#
    Call before `.\run-app.cmd` if Expo/Metro looks unhealthy. Same double-check
    discipline as Ensure-RentzuBackendClean - see its comment for why this
    matters. Prints a clear warning before killing anything.
    #>
    $portBound = [bool](Get-NetTCPConnection -LocalPort 8081 -State Listen -ErrorAction SilentlyContinue)
    if (-not $portBound) { return }
    if (Test-RentzuExpoHealthy) { return }
    Start-Sleep -Seconds 2
    if (Test-RentzuExpoHealthy) { return }
    Write-Warning "Expo/Metro on port 8081 is bound but failed health checks twice - stopping it so a fresh instance can start."
    Stop-ProcessOnPort -Port 8081
    Start-Sleep -Seconds 2
}

function Ensure-RentzuEmulatorClean {
    <# Kills a wedged/offline emulator so a fresh one can boot. No-op if a
       healthy booted emulator is already present - call Get-RunningEmulatorSerial
       first and only invoke this if it returned $null but `adb devices` still
       lists an "offline" entry. #>
    $offline = adb devices 2>$null | Select-String "^emulator-\d+\s+offline$"
    foreach ($line in $offline) {
        $serial = ($line -split '\s+')[0]
        adb -s $serial emu kill 2>$null | Out-Null
    }
    if ($offline) { Start-Sleep -Seconds 5 }
}

function Get-UiDump {
    <#
    Pulls a fresh uiautomator XML dump to a local file and returns its path.
    ALWAYS call this again after any action that can change layout: a tap that
    navigates, opening/closing the keyboard, a toast/snackbar appearing, etc.
    Cached bounds go stale the instant the keyboard opens or a screen transitions.
    #>
    param([string]$Name = "window")
    $remote = "/sdcard/$Name.xml"
    $local = Join-Path $script:RentzuUiWorkDir "$Name.xml"
    adb shell uiautomator dump $remote | Out-Null
    adb pull $remote $local 2>$null | Out-Null
    return $local
}

function Get-ElementBounds {
    <#
    Finds the first node in the most recent dump matching -Text (exact node "text=")
    or -ContentDesc (exact node "content-desc="), and returns @{X1;Y1;X2;Y2;CX;CY}.
    Throws if not found - check the raw XML with Grep/view if a lookup fails, UI
    text can differ by a trailing space, emoji prefix, or wrapping.
    #>
    param(
        [string]$DumpPath = (Join-Path $script:RentzuUiWorkDir "window.xml"),
        [string]$Text,
        [string]$ContentDesc
    )
    $xml = Read-XmlDump -Path $DumpPath
    $nodes = $xml.SelectNodes("//node")
    $match = $null
    foreach ($n in $nodes) {
        if ($Text -and $n.text -eq $Text) { $match = $n; break }
        if ($ContentDesc -and $n.'content-desc' -eq $ContentDesc) { $match = $n; break }
    }
    if (-not $match) { throw "Element not found (Text='$Text' ContentDesc='$ContentDesc') in $DumpPath" }
    if ($match.bounds -match '\[(\d+),(\d+)\]\[(\d+),(\d+)\]') {
        $x1 = [int]$Matches[1]; $y1 = [int]$Matches[2]; $x2 = [int]$Matches[3]; $y2 = [int]$Matches[4]
        return [pscustomobject]@{
            X1 = $x1; Y1 = $y1; X2 = $x2; Y2 = $y2
            CX = [int](($x1 + $x2) / 2); CY = [int](($y1 + $y2) / 2)
        }
    }
    throw "Could not parse bounds attribute: $($match.bounds)"
}

function Tap-Bounds {
    param([Parameter(Mandatory)]$Bounds, [int]$SettleMs = 400)
    adb shell input tap $Bounds.CX $Bounds.CY | Out-Null
    Start-Sleep -Milliseconds $SettleMs
}

function Tap-ElementByText {
    <# Convenience: dump -> find by visible text -> tap -> settle. #>
    param([Parameter(Mandatory)][string]$Text, [int]$SettleMs = 600)
    Get-UiDump | Out-Null
    $b = Get-ElementBounds -Text $Text
    Tap-Bounds -Bounds $b -SettleMs $SettleMs
}

function Tap-ElementByContentDesc {
    param([Parameter(Mandatory)][string]$ContentDesc, [int]$SettleMs = 600)
    Get-UiDump | Out-Null
    $b = Get-ElementBounds -ContentDesc $ContentDesc
    Tap-Bounds -Bounds $b -SettleMs $SettleMs
}

function Type-IntoFocusedField {
    <#
    Types into whatever EditText currently has focus. Call this immediately after
    the tap that focused the field - do not batch a tap and a type across a
    navigation boundary.

    Modified by AI on 07/24/2026. Edit #2. BUG THIS FIXES (found via SKILL.md §0.1's
    "no observable reaction" investigation rule while typing "22 Arch St" into a
    property-name field): `adb shell input text "$Text"` sends the string to the
    ANDROID DEVICE's shell, not the local one - that remote shell tokenizes on
    literal spaces as argument separators before `input text` ever sees them, so
    only the first word gets typed (e.g. "22 Arch St" silently became just "22",
    with no error - the exact class of silent no-op §0.1 requires diagnosing
    instead of retrying). Android's `input text`/`input keyboard text` command
    special-cases the literal token `%s` and decodes it back to a real space, so
    the fix is to substitute spaces with `%s` before they ever reach adb. Never
    revert this back to passing `$Text` with raw spaces to `adb shell input text`.
    #>
    param([Parameter(Mandatory)][string]$Text, [int]$SettleMs = 300)
    $escaped = $Text -replace ' ', '%s'
    adb shell input text "$escaped" | Out-Null
    Start-Sleep -Milliseconds $SettleMs
}

function Dismiss-Keyboard {
    param([int]$SettleMs = 400)
    adb shell input keyevent 111 | Out-Null  # KEYCODE_ESCAPE closes the soft keyboard
    Start-Sleep -Milliseconds $SettleMs
}

function Dismiss-RentzuMetroOverlay {
    <#
    Modified by AI on 07/18/2026. Edit #1. New helper: dismisses the RN LogBox
    "Cannot connect to Metro" overlay so it never gets mistaken for a real
    outage or blocks a downstream tap/detection.

    This is React Native's HMR/Fast-Refresh WebSocket client losing its dev
    connection to Metro - it is cosmetic noise, NOT a real backend/Expo outage
    (Get-RentzuSessionStatus stays healthy the whole time this is showing) and
    it does not block the JS bundle itself from loading. It shows in two forms:
      1. A small dismissible toast banner pinned near the bottom of the screen -
         closes with a plain `Dismiss-Keyboard` (KEYCODE_ESCAPE).
      2. An occasional FULL-SCREEN LogBox ("Console Warning: Cannot connect to
         Metro." + call stack) that KEYCODE_ESCAPE does NOT close - it needs an
         actual tap on its "Dismiss" button.
    Call this before any UI check (especially Confirm-RentzuLoggedIn) if a
    screenshot shows either form, since a full-screen LogBox covers the
    tabs/login-form markers those checks look for and produces a false
    "not logged in" / "element not found" result otherwise.
    #>
    param([int]$SettleMs = 500)
    Dismiss-Keyboard -SettleMs 200
    # Modified by AI on 07/25/2026. Edit #7.
    # Get-UiDump returns the dump FILE PATH (a string), not an [xml]. Calling
    # SelectSingleNode on it threw "[System.String] does not contain a method
    # named SelectSingleNode", which made this function fail outright instead of
    # dismissing the overlay. Parse the path through Read-XmlDump first.
    $dumpPath = Get-UiDump
    $xml = Read-XmlDump -Path $dumpPath
    $dismissNode = $xml.SelectSingleNode("//node[@text='Dismiss']")
    if ($dismissNode) {
        Tap-ElementByText "Dismiss"
        Start-Sleep -Milliseconds $SettleMs
    }
}

function Set-RentzuFieldValue {
    <#
    Reliably clears and types a value into a text field. Locate the field by
    -AnchorText (its placeholder, e.g. "you@example.com", "Create or enter your
    password", or "123456" for the OTP field - placeholder text stays stable
    across calls because it only shows while the field is empty).

    ALWAYS use this instead of a bare Tap-Bounds + Type-IntoFocusedField for any
    login/signup form field. It exists to work around two real bugs discovered
    while testing this skill - read both before changing this function:

    1. A Gboard floating "quick access" toolbar (mic / backspace-x / checkmark /
       emoji / hamburger icons, pinned vertically to the left edge) can appear
       after a burst of backspaces, and it PERSISTS ACROSS APP RESTARTS -
       confirmed via `adb shell dumpsys window windows` to be a system-level
       overlay tied to the `InputMethod` window, not something the RN app owns
       or can dismiss itself. NEVER dismiss it with the hardware back button
       (`adb shell input keyevent 4`): on the app's root screen (no back-stack
       yet), back navigation EXITS THE APP TO THE ANDROID HOME SCREEN instead of
       just closing the toolbar - far more disruptive than the toolbar itself,
       and it happened during testing. The correct dismissal is
       `adb shell input keyevent 111` (KEYCODE_ESCAPE - same as Dismiss-Keyboard):
       this collapses the keyboard AND the floating toolbar together, cleanly,
       every time it was tested. This function always clears via Dismiss-Keyboard,
       never back.
    2. Keyboard open/close and screen transitions shift every node's bounds.
       Tapping a *second* field (e.g. password) using bounds captured before the
       keyboard state changed can silently miss and leave focus on the FIRST
       field - so the second value gets typed onto the end of the first field's
       text instead, producing a garbled concatenation. Observed in practice:
       "vampirel1988@gmail.compassword123" all typed into the email field,
       password left empty, login rejected with "Please enter a valid email and
       password." This function re-dumps immediately before every tap and
       verifies (`focused='true'` in the fresh dump) that a field actually took
       focus before typing into it - never assume a tap landed correctly.

    Throws if a tap never focuses a field (screenshot and inspect - likely a
    system dialog, e.g. an ANR "System UI isn't responding" prompt, is covering
    the app; see SKILL.md "Known pitfalls" #7). Writes a warning (does not
    throw) if the typed value doesn't seem to have landed as expected, since a
    password field's echoed text may legitimately be masked/transformed.
    #>
    param(
        [Parameter(Mandatory)][string]$AnchorText,
        [Parameter(Mandatory)][string]$Value,
        [int]$MaxClearChars = 80
    )

    # Modified by AI on 07/24/2026. Edit #4. EFFICIENCY FIX (reported directly by
    # the user watching the emulator: "it tabs it and sidebar shows but then it
    # closes it loses focus and then 2nd time it tabs again and then enters the
    # text"). The old flow always did: tap -> clear via MOVE_END + up to 80x
    # KEYCODE_DEL -> Dismiss-Keyboard -> re-tap -> re-verify focus -> type. That
    # clear-then-retap round trip is pure waste here: -AnchorText only ever
    # matches a field's PLACEHOLDER text (see the docstring above and pitfall
    # #11), and a placeholder is only rendered while the field is genuinely
    # empty - the moment real text is typed the placeholder node disappears from
    # the dump, so a successful Get-ElementBounds match on -AnchorText already
    # guarantees there is nothing to clear. Doing the 80x-backspace-and-Dismiss-
    # Keyboard dance on an already-empty field just opens/closes the keyboard
    # (and the Gboard sidebar it drags along, pitfall #9/#13) for nothing, then
    # taps a second time and reopens it again before finally typing - visibly
    # flickering the sidebar in/out with no functional benefit. Fix: tap once,
    # confirm focus, type directly. If a genuinely non-empty field ever needs
    # clearing, that's a different, rarer operation - do not reintroduce the
    # blind clear-every-time behavior here to "be safe"; it was never needed for
    # this function's actual (placeholder-anchored) use case.
    Get-UiDump | Out-Null
    $bounds = Get-ElementBounds -Text $AnchorText
    Tap-Bounds $bounds
    Start-Sleep -Milliseconds 700

    Get-UiDump | Out-Null
    $xml = Read-XmlDump -Path (Join-Path $script:RentzuUiWorkDir "window.xml")
    if (-not $xml.SelectSingleNode("//node[@focused='true']")) {
        throw "Set-RentzuFieldValue: tapping '$AnchorText' did not focus any field - screenshot and inspect (a system dialog may be covering the app)."
    }

    Type-IntoFocusedField $Value

    # Modified by AI on 07/25/2026. Edit #5. BUG THIS FIXES (pitfall #15, reported by
    # the user watching a ForceReLogin: the email was typed as
    # "vvampirel1988@gmail.com" - a DOUBLED leading character - which silently
    # created/logged into a brand-new EMPTY account instead of the real test
    # account). Root cause: `adb shell input text` sent immediately after a field
    # gains focus races the emulator IME coming up, and the emulator intermittently
    # DUPLICATES the first character (and can mis-key a masked field). A single blind
    # type is therefore not trustworthy for the one field whose exact value actually
    # matters - the email, which determines WHICH account you log into (since auth
    # was hardened a mistyped password fails with 401 at "Continue with email", but
    # a mistyped email registers a brand-new empty account). Fix: for readable
    # (non-masked) fields, read the field back from a fresh dump and, if it doesn't
    # exactly equal the requested value, clear it (MOVE_END + backspaces) and retype
    # - up to 3 attempts - then THROW rather than silently proceed with a wrong
    # value. Masked fields (password) can't be read back, so they keep a best-effort
    # warning only. Never revert this to a single blind type + warning.
    $typedOk = $false
    for ($attempt = 1; $attempt -le 3; $attempt++) {
        Get-UiDump | Out-Null
        $xmlV = Read-XmlDump -Path (Join-Path $script:RentzuUiWorkDir "window.xml")
        $focused = $xmlV.SelectSingleNode("//node[@focused='true']")
        $shown = if ($focused) { [string]$focused.text } else { '' }
        $isMasked = $shown -match '^[\u2022\u00b7\*]+$'
        if (-not $focused) { $typedOk = $true; break }        # lost focus - can't verify, don't loop
        if ($isMasked)     { $typedOk = $true; break }        # masked field - can't read back
        if ($shown -eq $Value) { $typedOk = $true; break }    # exact match - success
        # Mismatch on a readable field (e.g. a duplicated first char): clear + retype.
        adb shell input keyevent 123 | Out-Null              # KEYCODE_MOVE_END
        for ($i = 0; $i -lt ($shown.Length + 4); $i++) { adb shell input keyevent 67 | Out-Null }  # KEYCODE_DEL
        Start-Sleep -Milliseconds 250
        Type-IntoFocusedField $Value
    }
    if (-not $typedOk) {
        Get-UiDump | Out-Null
        $xmlF = Read-XmlDump -Path (Join-Path $script:RentzuUiWorkDir "window.xml")
        $finalNode = $xmlF.SelectSingleNode("//node[@focused='true']")
        $finalText = if ($finalNode) { [string]$finalNode.text } else { '' }
        throw "Set-RentzuFieldValue: field '$AnchorText' shows '$finalText' after 3 attempts (expected '$Value') - emulator IME likely duplicated/dropped characters."
    }

    # Modified by AI on 07/24/2026. Edit #3. BUG THIS FIXES (pitfall #13, found via
    # SKILL.md §0.1's "no observable reaction" rule after a Fourplex-selection tap
    # silently missed following a typed field): Gboard's floating "quick access"
    # toolbar (mic/backspace/checkmark/emoji/hamburger icons pinned to the left
    # edge - see pitfall #9) is a separate system `InputMethod` window, confirmed
    # via `adb shell dumpsys window windows`, so it never appears in a uiautomator
    # dump and can't be detected/asserted-away there. It opens as soon as a field
    # is focused (not only after a backspace burst) and stays open - along with
    # the soft keyboard - after this function returns, silently covering the left
    # edge of the screen and any stale-bounds tap landing there (or animating
    # closed mid-tap) until something explicitly closes it. Always leave the
    # keyboard/toolbar closed before handing control back to the caller so the
    # next Tap-* call starts from a clean state instead of guessing whether it's
    # still open.
    Dismiss-Keyboard
}

function Take-Screenshot {
    <# Pulls a PNG next to the XML dumps and returns its local path for the `view` tool. #>
    param([string]$Name = "screen")
    $remote = "/sdcard/$Name.png"
    $local = Join-Path $script:RentzuUiWorkDir "$Name.png"
    adb shell screencap -p $remote | Out-Null
    adb pull $remote $local 2>$null | Out-Null
    return $local
}

function Wait-ForEmulatorBoot {
    param([int]$TimeoutSec = 120)
    $elapsed = 0
    while ($elapsed -lt $TimeoutSec) {
        $booted = adb shell getprop sys.boot_completed 2>$null
        if ($booted -match "1") { return $true }
        Start-Sleep -Seconds 3
        $elapsed += 3
    }
    throw "Emulator did not report sys.boot_completed=1 within $TimeoutSec s"
}

function Confirm-RentzuLoggedIn {
    <#
    Read-only check: dumps the current UI and returns $true if the app is showing
    the authenticated tab navigator (any of Summary/Property/Tax Ready/Account are
    present), $false if it's on the login/verify form, and $false for anything
    unrecognized (caller should screenshot in that case - it may be a loading
    spinner, an error boundary, or a modal). Never throws.

    BUG THIS FIXES: right after opening the app (fresh `adb shell am start` deep
    link, or right after Metro finishes a rebuild), there is a real window - often
    several seconds - where the app is on a splash/loading screen showing neither
    the authenticated tabs nor the login form. A single immediate dump can land
    exactly in that window and falsely conclude "not logged in", which then sends
    Invoke-RentzuLogin down the login-form path even though the app is actually
    already authenticated underneath (this happened in practice: a persisted JWT
    from a prior session survived a full backend/Expo/emulator restart because
    Expo Go's storage lives on the emulator disk, not the dev server). To avoid
    that race, this function polls for up to $TimeoutSec, re-dumping every
    $PollIntervalSec, and only returns once it sees a DEFINITIVE signal - either
    the authenticated tab bar, or a recognizable login/verify screen marker. If
    neither ever appears before the timeout, it gives up and returns $false (the
    old fallback behavior), but logs a warning so the caller/log isn't silently
    misled - screenshot and inspect manually in that case.
    #>
    param(
        [int]$TimeoutSec = 20,
        [int]$PollIntervalSec = 2
    )
    $elapsed = 0
    while ($true) {
        Get-UiDump | Out-Null
        $xml = Read-XmlDump -Path (Join-Path $script:RentzuUiWorkDir "window.xml")
        # Auto-heal: a full-screen "Cannot connect to Metro" LogBox (cosmetic HMR
        # WebSocket noise, not a real outage - see Dismiss-RentzuMetroOverlay)
        # covers every tab/login marker below and would otherwise be
        # misread as "app stuck loading" for the whole timeout.
        if ($xml.SelectNodes("//node[@text='Cannot connect to Metro.']").Count -gt 0) {
            Dismiss-RentzuMetroOverlay
        } else {
            foreach ($desc in @("Summary", "Property", "Tax Ready", "Account")) {
                if ($xml.SelectNodes("//node[@content-desc='$desc']").Count -gt 0) { return $true }
            }
            foreach ($marker in @("you@example.com", "Continue with email", "Verify your email")) {
                if ($xml.SelectNodes("//node[@text='$marker']").Count -gt 0) { return $false }
            }
        }
        if ($elapsed -ge $TimeoutSec) {
            Write-Warning "Confirm-RentzuLoggedIn: no definitive signal (tabs or login form) after ${TimeoutSec}s - app may still be loading, on an error screen, or showing a system dialog. Screenshot and inspect manually. Defaulting to `$false."
            return $false
        }
        Start-Sleep -Seconds $PollIntervalSec
        $elapsed += $PollIntervalSec
    }
}

function Get-RentzuVerificationCode {
    <#
    Returns the newest PENDING 6-digit verification code for $Email by reading
    the email_verification_codes table directly.

    WHY THIS EXISTS: verification codes are now randomly generated per request
    and delivered only by SMTP - the old RENTZU_FIXED_VERIFICATION_CODE=123456
    dev bypass was removed because it allowed anyone who could reach the API to
    log into any account. Automated tests therefore can't hardcode a code any
    more. Reading it from Postgres keeps the test flow fully automatic while
    requiring local DB access, so it is not a remotely exploitable bypass.

    The row is written by POST /auth/request-code, so only call this AFTER
    tapping "Continue with email". Polls briefly because the HTTP request (which
    includes a real SMTP send) may still be in flight.
    #>
    param(
        [string]$Email = "vampirel1988@gmail.com",
        [int]$TimeoutSeconds = 45
    )

    $python = "D:\apps\rentzu\.venv\Scripts\python.exe"
    $script = Join-Path $PSScriptRoot "get-verification-code.py"

    if (-not (Test-Path $python)) { throw "Python venv not found at $python" }
    if (-not (Test-Path $script)) { throw "Helper not found at $script" }

    $deadline = (Get-Date).AddSeconds($TimeoutSeconds)
    $lastError = ""

    while ((Get-Date) -lt $deadline) {
        $output = & $python $script $Email 2>&1
        $code = ($output | Where-Object { $_ -match '^\d{6}$' } | Select-Object -First 1)
        if ($code) { return "$code".Trim() }
        $lastError = ($output | Out-String).Trim()
        Start-Sleep -Seconds 2
    }

    throw "Could not read a pending verification code for $Email within $TimeoutSeconds s. Last output: $lastError"
}

function Invoke-RentzuLogin {
    <#
    IDEMPOTENT base login flow - this is the single entry point every downstream
    test skill should call first, every time, with no preconditions assumed.

    - If the app is already authenticated (Confirm-RentzuLoggedIn -eq $true), this
      returns immediately without touching anything - it will NOT sign out and
      re-login just because it was called again. This is what lets a chain of
      test skills each call Invoke-RentzuLogin at the start of their own script
      and continue seamlessly from wherever the previous skill left off, instead
      of restarting the whole flow and losing in-progress state.
    - Pass -ForceReLogin to explicitly sign out and log back in even if already
      authenticated (useful for a skill that specifically tests the logout/login
      cycle itself).
    - On success, leaves the app on the Summary tab of the authenticated tab
      navigator.

    Throws if any expected element is missing or verification fails - treat that
    as a hard failure of the login flow, not something to silently retry past.
    #>
    param(
        [string]$Email = "vampirel1988@gmail.com",
        [string]$Password = "password123",
        [string]$Code = "",
        [switch]$ForceReLogin
    )

    $isLoggedIn = Confirm-RentzuLoggedIn

    if (-not $ForceReLogin -and $isLoggedIn) {
        Write-Verbose "Invoke-RentzuLogin: already authenticated, reusing session as-is."
        return
    }

    # BUG THIS FIXES: "Sign Out" only exists as a node on the Account tab, not on
    # whichever tab the app happens to be showing. Checking for it in whatever
    # dump is currently cached (e.g. still on Summary from a prior session) always
    # finds nothing, silently skips the sign-out tap, and falls through to the
    # email-field lookup below - which then throws because the app is still
    # showing the authenticated Summary screen, not the login form. So only when
    # we've CONFIRMED the app is authenticated ($isLoggedIn, from the tab-navigator
    # check above - not just "-ForceReLogin was passed", since a not-logged-in app
    # has no tabs to navigate at all) do we navigate to the Account tab and sign
    # out first.
    if ($isLoggedIn) {
        Get-UiDump | Out-Null
        Tap-ElementByText "Account"
        Start-Sleep -Seconds 1
        Get-UiDump | Out-Null
        $xml = Read-XmlDump -Path (Join-Path $script:RentzuUiWorkDir "window.xml")
        $signedIn = $xml.SelectNodes("//node[@content-desc='Sign Out']").Count -gt 0
        if ($signedIn) {
            Tap-ElementByText "Sign Out"
            Start-Sleep -Seconds 1
        }
    }

    # At this point we expect the "Get into your portfolio" login form. If neither
    # a signed-in Account screen nor the login form is present, the caller is in an
    # unrecognized state - screenshot and inspect before calling this function.
    Set-RentzuFieldValue -AnchorText "you@example.com" -Value $Email
    Set-RentzuFieldValue -AnchorText "Create or enter your password" -Value $Password
    Dismiss-Keyboard  # "Continue with email" can be covered by the keyboard otherwise

    Get-UiDump | Out-Null
    Tap-ElementByText "Continue with email"

    # Verification codes are random per request and sent by email, so the code
    # must be read from the DB *after* /auth/request-code has run. An explicit
    # -Code still wins, for tests that deliberately submit a wrong code.
    if ([string]::IsNullOrWhiteSpace($Code)) {
        $Code = Get-RentzuVerificationCode -Email $Email
        Write-Verbose "Invoke-RentzuLogin: fetched verification code for $Email."
    }

    # Verification screen. The code field's placeholder text is literally "123456".
    Set-RentzuFieldValue -AnchorText "123456" -Value $Code
    Dismiss-Keyboard  # "Verify email" can be covered by the keyboard otherwise

    Get-UiDump | Out-Null
    Tap-ElementByText "Verify email"

    Start-Sleep -Seconds 2
    Get-UiDump | Out-Null
    $after = Read-XmlDump -Path (Join-Path $script:RentzuUiWorkDir "window.xml")
    $stillOnVerify = $after.SelectNodes("//node[@text='Verify your email']").Count -gt 0
    if ($stillOnVerify) {
        throw "Login did not complete - still on verification screen. Screenshot and inspect for 'Invalid verification code'."
    }
}

function Resume-RentzuSession {
    <#
    THE single entry point for every downstream test skill. Safe to call at the
    top of any independent `powershell` tool call, any number of times, in any
    order relative to other skills - it never tears anything down, only checks
    and (if truly necessary) repairs.

    What it does, in order:
      1. Get-RentzuSessionStatus - authoritative OS-level health check of backend
         (port 8000), Expo (port 8081), and the emulator.
      2. If backend or Expo is bound-but-unhealthy (stale process from a crashed
         run), cleans just that port. It does NOT start run-server.cmd/run-app.cmd
         itself - starting those is a top-level `powershell` tool call so their
         logs stream to the user (see SKILL.md "Visibility requirement"). If this
         function reports a component as not healthy and not just "needs a port
         cleaned", the caller must start it themselves with the documented
         run-server.cmd / run-app.cmd / emulator.exe commands and re-check.
      3. Confirm-RentzuLoggedIn - if not logged in, calls Invoke-RentzuLogin.
      4. Returns a status object the caller can inspect/log.

    Example (top of a downstream skill's script, after re-dot-sourcing this file):
        $status = Resume-RentzuSession
        if (-not $status.Ready) { throw "Environment not ready: $($status | ConvertTo-Json)" }
        # ... continue this skill's own test steps from here, app is authenticated ...
    #>
    param(
        [string]$Email = "vampirel1988@gmail.com",
        [string]$Password = "password123",
        [string]$Code = ""
    )

    Ensure-RentzuBackendClean
    Ensure-RentzuExpoClean
    $status = Get-RentzuSessionStatus

    $ready = $status.BackendHealthy -and $status.ExpoHealthy -and $status.EmulatorRunning
    $loggedIn = $false
    if ($ready) {
        Invoke-RentzuLogin -Email $Email -Password $Password -Code $Code
        $loggedIn = Confirm-RentzuLoggedIn
    }

    [pscustomobject]@{
        Ready          = $ready
        LoggedIn       = $loggedIn
        BackendHealthy = $status.BackendHealthy
        ExpoHealthy    = $status.ExpoHealthy
        EmulatorSerial = $status.EmulatorSerial
    }
}

