-- Generated by AI on 07/18/2026
-- Adds a 'mortgage' (principal) category. Mortgage/loan interest continues to use
-- the existing 'interest' category (deductible, Schedule E line 12); 'mortgage'
-- tracks the non-deductible principal portion for cash-flow reporting.

begin;

alter table financial_records drop constraint if exists financial_records_category_code_check;

alter table financial_records
add constraint financial_records_category_code_check
check (
    category_code is null or category_code in (
        'rent',
        'additional_income',
        'legal',
        'utility',
        'cleaning',
        'management',
        'maintenance',
        'repair',
        'other',
        'travel',
        'commission',
        'interest',
        'mortgage',
        'improvement',
        'insurance',
        'tax'
    )
);

commit;
