-- Generated by AI on 07/25/2026.
-- Adds RevenueCat (native iOS/Android in-app purchase) support alongside the
-- existing Stripe (web) billing columns, per pricing_research.md's
-- "Native mobile billing (RevenueCat)" section. Idempotent: safe to re-run.

alter table organization_billing
  add column if not exists billing_provider text not null default 'stripe';

alter table organization_billing
  add column if not exists revenuecat_app_user_id text;

alter table organization_billing
  add column if not exists revenuecat_entitlement_id text;

alter table organization_billing
  add column if not exists revenuecat_product_id text;

alter table organization_billing
  add column if not exists revenuecat_store text;

create table if not exists revenuecat_events (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references organizations(id) on delete cascade,
  revenuecat_event_id text not null unique,
  revenuecat_event_type text not null,
  app_user_id text,
  product_id text,
  entitlement_ids text,
  period_type text,
  store text,
  occurred_at timestamptz,
  raw_payload text,
  created_at timestamptz not null default now()
);

create index if not exists revenuecat_events_organization_id_idx on revenuecat_events (organization_id);
