-- Generated by AI on 07/18/2026
-- Adds plan-tier + voice-quota tracking columns to organization_billing.
-- Required because SQLAlchemy's Base.metadata.create_all() only creates
-- missing tables, not missing columns on tables that already exist.

begin;

alter table organization_billing
    add column if not exists plan text not null default 'free';

alter table organization_billing
    add column if not exists billing_interval text not null default 'month';

alter table organization_billing
    add column if not exists voice_quota_period_start timestamptz;

alter table organization_billing
    add column if not exists voice_used_this_period integer not null default 0;

alter table organization_billing drop constraint if exists organization_billing_plan_check;
alter table organization_billing
    add constraint organization_billing_plan_check
    check (plan in ('free', 'normal', 'pro'));

alter table organization_billing drop constraint if exists organization_billing_billing_interval_check;
alter table organization_billing
    add constraint organization_billing_billing_interval_check
    check (billing_interval in ('month', 'year'));

commit;
