# Generated by AI on 07/03/2026
"""User profile business logic (kept out of the router per repo conventions)."""

from __future__ import annotations

from sqlalchemy.orm import Session

from models.user import User


def update_language_preference(db: Session, user: User, language_preference: str) -> User:
    """Persist the user's preferred app language ('en' or 'zh')."""
    user.language_preference = language_preference
    db.add(user)
    db.commit()
    db.refresh(user)
    return user
